format_version: '2.0'

input_files: 'CWE761_Free_Pointer_Not_at_Start_of_Buffer---CWE761_Free_Pointer_Not_at_Start_of_Buffer__char_environment_15_good.i'

properties:
  - property_file: ../properties/valid-memsafety.prp
    expected_verdict: true

options:
  language: C
  data_model: LP64
